- .travis.yml
- CHANGELOG.md
Resolves https://github.com/iov-one/iovns/issues/196
@davepuchyr please merge after approval.
> Enable gitian on travis builds

- .travis.yml
> Fix travis gitian build

- .travis.yml
> Attempt to fix gitian build

- x/configuration/genesis.go
> Fix default testnet genesis product fee denom

- x/domain/client/rest/routes.go
> Fix domain tx routes

- CHANGELOG.md
- x/configuration/client/rest/doc.go
- x/configuration/client/rest/routes.go
- x/configuration/client/rest/tx.go
- x/configuration/module.go
- x/configuration/query.go
Resolves https://github.com/iov-one/iovns/issues/29
> Add configuration module rest features

- CHANGELOG.md
- x/domain/client/cli/query.go
- x/domain/client/cli/tx.go
Resolves https://github.com/iov-one/iovns/issues/220
> Rename query resolve-domain to domain-info, resolve-account to account

- CHANGELOG.md
- x/domain/types/types.go
Resolves https://github.com/iov-one/iovns/issues/210
> Rename account target id to blockchain id

- .travis.yml
> Update main build go minor version

- x/domain/client/rest/routes.go
!nochangelog
this will fix the issue in https://github.com/iov-one/easy-testnets/issues/108#issuecomment-645404730
> Fix tx routes

- CHANGELOG.md
- Dockerfile.dev
- x/configuration/client/cli/query.go
- x/configuration/types/queries.go
solves: https://github.com/iov-one/iovns/issues/227
> fix: configuration get config

- CHANGELOG.md
- cmd/iovnscli/clitests/domain_register_account.test.gold
- cmd/iovnscli/clitests/domain_register_domain.test.gold
- cmd/iovnscli/clitests/domain_replace_account_targets.test.gold
- cmd/iovnscli/clitests/new_account_targets.json
- x/domain/client/cli/tx.go
Resolves https://github.com/iov-one/easy-testnets/issues/128
> Add broker field to registerDomain and registerAccount

- CHANGELOG.md
- Dockerfile.dev
- scripts/cli/.envrc
- scripts/cli/add-account-certs.sh
- scripts/cli/fees.json
- scripts/cli/register-account.sh
- scripts/cli/register-domain.sh
- scripts/cli/replace-account-target.sh
- scripts/cli/set-metadata-uri.sh
- scripts/cli/transfer-domain.sh
- x/configuration/types/fees.go
- x/domain/account_handlers.go
- x/domain/controllers/fees/controller.go
- x/domain/controllers/fees/controller_test.go
- x/domain/domain_handlers.go
- x/domain/keeper/fees.go
- x/domain/keeper/test_common.go
This PR fixes the fee calculation mismatch. I started writing tests for fee controller. We should expand it.
> Fix fee deduct

- CHANGELOG.md
- x/domain/keeper/domain.go
- x/domain/keeper/domain_test.go
Resolves https://github.com/iov-one/iovns/issues/233
> TransferDomain flush empty account data

- x/domain/keeper/domain.go
- x/domain/keeper/domain_test.go
> Fix master

- CHANGELOG.md
> Release v0.4.4

- .travis.yml
- CHANGELOG.md
- cmd/faucet/.gitignore
- cmd/faucet/Dockerfile
- cmd/faucet/Makefile
- cmd/faucet/README.md
- cmd/faucet/main.go
- cmd/faucet/pkg/codec.go
- cmd/faucet/pkg/config.go
- cmd/faucet/pkg/handlers.go
- cmd/faucet/pkg/txmanager.go
- cmd/faucet/pkg/txmanager_test.go
- go.mod
- go.sum
Resolves https://github.com/iov-one/iovns/issues/51
> Implement faucet

- CHANGELOG.md
- x/domain/controllers/domain/domain.go
- x/domain/controllers/domain/domain_test.go
Resolves https://github.com/iov-one/easy-testnets/issues/98
> Fix domain renewal

- .travis.yml
- CHANGELOG.md
- cmd/faucet/main.go
- go.mod
- go.sum
> change: update tendermint and cosmos-sdk versions

- CHANGELOG.md
- Dockerfile.dev
- go.mod
- go.sum
- scripts/accounts.sh
- scripts/entrypoint.sh
- x/starname/keeper/executor/domain_test.go
- x/starname/keeper/queries.go
> Upgrade to cosmos sdk 0.39

- CHANGELOG.md
- pkg/crud/internal/store/keyset.go
- pkg/crud/internal/store/store.go
finally... thanks @davepuchyr for bringing this up
> fix filtering

- CHANGELOG.md
- scripts/integration/test/CLI.test.js
- x/starname/domain_handlers.go
- x/starname/domain_handlers_test.go
> allow open domain transfers

- scripts/genesis/package.json
- scripts/genesis/rebate.sh
- scripts/genesis/rebates.js
- scripts/genesis/yarn.lock
We promised to send rebates to users that registered their star1 address in https://medium.com/iov-internet-of-values/if-you-are-an-iov-token-holder-please-read-carefully-below-what-you-need-to-do-before-our-b0783fe7102b.
> Send rebates to those that registered a star1 address

- scripts/genesis/lib/migrate.js
- scripts/genesis/test/lib/fetchIndicativeSendsTo.test.js
- scripts/genesis/test/lib/migrate.test.js
Reserved domains will expire on a mid-month Wednesday unless they're transferred to a new owner.
> Stagger expiry dates on reserved domains

- scripts/genesis/holdings.js
- scripts/genesis/lib/migrate.js
- scripts/genesis/test/lib/migrate.test.js
> Generate output similar to holdings.csv

- CHANGELOG.md
- scripts/integration/test/CLI.test.js
- x/starname/keeper/executor/domain.go
- x/starname/keeper/executor/main_test.go
> fix: empty account renewal

- scripts/genesis/genesis.js
- scripts/genesis/lib/migrate.js
- scripts/genesis/test/lib/migrate.test.js
Fix Error [MinimongoError]: Key //timeout 2029-11-10T00:00:00.000Z must not contain '.'.
> Make Big Dipper happy with the genesis file

- CHANGELOG.md
- x/configuration/client/cli/tx.go
Read the current fees from the chain, selectively replace the specified fee parameters, and then submit the updated fees to the chain.
> Add iovnscli command update-fee
